### ISSUE TITLE
qtranxf_convertURL() issue with default Language

### ISSUE THREAD

**Issue by herrvigg** [herrvigg/qtranslate-x#161]
<a href="https://github.com/fabiangarga"><img src="https://avatars0.githubusercontent.com/u/5950950?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [fabiangarga](https://github.com/fabiangarga)**
_Tuesday May 19, 2015 at 21:05 GMT_
_Originally opened as https://github.com/qTranslate-Team/qtranslate-x/issues/161_

----

Hi i think there is an issue with this function.

To reproduce this error you have to check the option "Hide URL language information for default language." on advanced settings.

If i use qtranxf_convertURL(URL, Default_Language) it will give me the url without the language code in the URL, but with this doesn't change to the default language if im already on other language.

For example if my default language is German, and im on the English version of the website, if i click on the German link it will stay on the english version.
If i disable to hide the URL of the default language, the url will be always returned with the language prefix, and will work.

Is there any way to fix this?

**Comment by herrvigg** [comment]
<a href="https://github.com/johnclause"><img src="https://avatars2.githubusercontent.com/u/5491361?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [johnclause](https://github.com/johnclause)**
_Wednesday May 20, 2015 at 00:23 GMT_

----

This function has additional argument `$showDefaultLanguage`, which when set to true will always encode URL with a language, otherwise it senses option "Hide URL language information for default language" to keep URL consistent with the currently chosen language.

If you need a URL to switch the language, set $showDefaultLanguage=true, if you need a URL to keep the current language, set it to false.

I am closing this issue for now, we can still write into a closed issue, or we can re-open it, if needed.

**Comment by herrvigg** [comment]
<a href="https://github.com/fabiangarga"><img src="https://avatars0.githubusercontent.com/u/5950950?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [fabiangarga](https://github.com/fabiangarga)**
_Wednesday May 20, 2015 at 17:24 GMT_

----

I didn't know that.
Thanks a lot for the reply!

**Comment by antonzol** [comment]
Have same task now.
Can I in anyway leave showDefaultLanguage=false and switch the language to German by clicking on language swith button?
If German is default and "Hide URL language information for default language" as in this example?
