### ISSUE TITLE
PHP warning in qtx_admin.php on line 31

### ISSUE THREAD

**Issue by herrvigg** [herrvigg/qtranslate-x#217]
<a href="https://github.com/dirkgeeroms"><img src="https://avatars2.githubusercontent.com/u/13780530?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dirkgeeroms](https://github.com/dirkgeeroms)**
_Thursday Aug 13, 2015 at 11:03 GMT_
_Originally opened as https://github.com/qTranslate-Team/qtranslate-x/issues/217_

----

I recently installed qTranslate X on my wordpress website test.dirkgeeroms.be.
I got the following PHP warnings:
1) PHP Warning: Unknown: Input variables exceeded 1000. To increase the limit change max_input_vars in php.ini. in Unknown on line 0 
2) PHP Warning: Invalid argument supplied for foreach() in /www/test.dirkgeeroms.be/wp-content/plugins/qtranslate-x/admin/qtx_admin.php on line 31

The first one was easy to get rid off. But do I have to care about the second one? If so, how could I resolve it?

Cheers, Dirk

**Comment by herrvigg** [comment]
<a href="https://github.com/johnclause"><img src="https://avatars2.githubusercontent.com/u/5491361?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [johnclause](https://github.com/johnclause)**
_Thursday Aug 13, 2015 at 22:46 GMT_

----

Thanks a lot for the report. The first one is described in https://qtranslatexteam.wordpress.com/troubleshooting/, it is frequently a case when max_input_vars needs to be increased.

The second issue is a consequence of the first. If you still see the second warning, then yes, there is a problem which we need to attend on your configuration.

I am closing this issue for now, we can still write to closed issue and may reopen it when needed.

**Comment by fuvavi** [comment]
Delete '&' line 24 wp-content\plugins\qtranslate-x\admin\qtx_admin.php
function qtranxf_collect_translations( &$qfields, &$request, &$edit_lang )
=> function qtranxf_collect_translations( $qfields, $request, $edit_lang )

**Comment by herrvigg** [comment]
hello,
i would like to help but we have to be very cautious here . It's not just about removing some warnings, we need to understand precisely the code and this part is quite tricky. Note the function is recursive and used in many places. If i remove the reference the function will behave differently and not returning the changes on `&$qfields` and `&$request` (`$edit_lang` should not have any ampersand). I don't think i can do that without changing other parts. 

First of all, what is the issue? Personally i don't have such warnings and i'm with the last versions of WP and PHP 7.2. According to the link i sent previously, this is related to `max_input_vars`. Did you check that?
