### ISSUE TITLE
Cant download plugin - It isn't showing on Wordpress Directory

### ISSUE THREAD

**Issue by herrvigg** [herrvigg/qtranslate-x#234]
<a href="https://github.com/Cajucaju"><img src="https://avatars0.githubusercontent.com/u/13997040?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Cajucaju](https://github.com/Cajucaju)**
_Thursday Aug 27, 2015 at 10:30 GMT_
_Originally opened as https://github.com/qTranslate-Team/qtranslate-x/issues/234_

----

Hi, I've used this plguin before, but seems it's no longer on the Wordpress Plugin Directory, see the link on your description:

https://wordpress.org/plugins/qtranslate-x/

How can I download it?

Thanks!

**Comment by herrvigg** [comment]
<a href="https://github.com/Grafcom"><img src="https://avatars0.githubusercontent.com/u/11356362?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Grafcom](https://github.com/Grafcom)**
_Thursday Aug 27, 2015 at 10:45 GMT_

----

@Cajucaju
We are currently working on a solution to get this again on the Wordpress Plugin Directory.
Download for now the plugin here
https://github.com/qTranslate-Team/qtranslate-x/archive/master.zip
- Do not use install via WordPress admin!
  First unzip the new file.
  Deactivate the existing version of qTranslate in WordPress admin.
  Then with FTP delete all files in the existing qtranslate-x folder and after that copy all new files in it.
  Activate qTranslate-x again via WordPress admin.

**Comment by herrvigg** [comment]
<a href="https://github.com/Cajucaju"><img src="https://avatars0.githubusercontent.com/u/13997040?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Cajucaju](https://github.com/Cajucaju)**
_Thursday Aug 27, 2015 at 11:03 GMT_

----

Thanks Grafcom, I did exactly what you've said, and it worked, but I keep getting this message:

Error: plugin qTranslate‑X cannot run concurrently with plugin qTranslate. You may import and export compatible settings between qTranslate‑X and qTranslate on Settings/Languages configuration page. Then you have to deactivate one of the plugins to continue. It might be a good idea to review migration instructions, if you have not yet done so.

The thing is, it is a fresh installation, and, I've seen the Migration instructions, but couldnt seem to find some issue like that.

Thanks again!

**Comment by herrvigg** [comment]
<a href="https://github.com/Grafcom"><img src="https://avatars0.githubusercontent.com/u/11356362?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Grafcom](https://github.com/Grafcom)**
_Thursday Aug 27, 2015 at 11:11 GMT_

----

@Cajucaju
for a fresh installation you need to rename the master folder from qTranslate x.
- First unzip the file and you get a folder with the name qtranslate-x-master.
  In the folder there is another folder with the name qtranslate-x-master.
  This folder contains all the files of the plugin. Rename this folder to qtranslate-x and zip this folder.
- Deactivate qTranslate X in WP Admin and delete it. 

Deactivate mqTranslate, qTranslate Plus, qTranslate, zTranslate or any other multilingual plugin, which you previously used.
- Now upload the qtranslate-x zip file

**Comment by herrvigg** [comment]
<a href="https://github.com/Cajucaju"><img src="https://avatars0.githubusercontent.com/u/13997040?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Cajucaju](https://github.com/Cajucaju)**
_Thursday Aug 27, 2015 at 12:19 GMT_

----

Yes Grafcom, thank you so much!

This plugin is, for me, the best.

Expect my donation!

My best

**Comment by PanderMusubi** [comment]
@herrvigg "We are currently working on a solution to get this again on the Wordpress Plugin Directory."

Can you give an update of this? Thanks.

**Comment by herrvigg** [comment]
hello,
i migrated these old issues from qTranslate-X but i didn't answer myself (see original author in the attachment). 
About qTranslate-XT see rather this one: https://github.com/qtranslate/qtranslate-xt/issues/601. I will give a few updates there.
