### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by herrvigg** [herrvigg/qtranslate-x#289]
<a href="https://github.com/blerimkrosi"><img src="https://avatars2.githubusercontent.com/u/5637169?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [blerimkrosi](https://github.com/blerimkrosi)**
_Sunday Oct 18, 2015 at 12:31 GMT_
_Originally opened as https://github.com/qTranslate-Team/qtranslate-x/issues/289_

----

I get this error but from my server say its the probleb of script and when I deactivate qTranslate plugin the site works but is disconfugirated,,,

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator, webmaster@ibc.link and inform them of the time the error occurred, and anything you might have done that may have caused the error.

More information about this error may be available in the server error log.

Additionally, a 500 Internal Server Error error was encountered while trying to use an ErrorDocument to handle the request.

**Comment by herrvigg** [comment]
<a href="https://github.com/blerimkrosi"><img src="https://avatars2.githubusercontent.com/u/5637169?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [blerimkrosi](https://github.com/blerimkrosi)**
_Sunday Oct 18, 2015 at 12:33 GMT_

----

this is the site: http://ibc.link/market/

**Comment by herrvigg** [comment]
<a href="https://github.com/johnclause"><img src="https://avatars2.githubusercontent.com/u/5491361?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [johnclause](https://github.com/johnclause)**
_Sunday Oct 18, 2015 at 14:48 GMT_

----

Please, correct your .htaccess file. Indeed there is a bug in qtx which causes .htaccess to be overridden incorrectly under some circumstances: https://wordpress.org/support/topic/internal-server-error-500-after-346-update

It is already corrected in the latest version of [GitHub](https://github.com/qTranslate-Team/qtranslate-x) and will be released shortly.

I am closing this issue for now to save the future clicks, we can still write into a closed issue, or we can re-open it, if your case is related to something else.

**Comment by herrvigg** [comment]
<a href="https://github.com/blerimkrosi"><img src="https://avatars2.githubusercontent.com/u/5637169?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [blerimkrosi](https://github.com/blerimkrosi)**
_Sunday Oct 18, 2015 at 18:44 GMT_

----

I need also help how to translate manualy mostly of words as "Cart (1 Item)", "Add to cart", and a lot of others om cart page: http://ibc.link/market/es/cart/ I dont know were to find them!!!

**Comment by herrvigg** [comment]
<a href="https://github.com/johnclause"><img src="https://avatars2.githubusercontent.com/u/5491361?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [johnclause](https://github.com/johnclause)**
_Monday Oct 19, 2015 at 04:54 GMT_

----

Please, do not place different topics under the same issue - think about the readers and people who searches some answers later after you.

> but after few minutes the .htacces changes itself

Yes, it will change on almost every new plugin install or WP update and if a few options are set on a specific way, which is apparently happened on your site. Sorry about this, please, update to the latest version from GitHub.

> does the problem comes because i did not pay any donations??

Ha-Ha! LOL! You gave an idea!

> but i noticed few other changes

That I do not know, probably and hopefully unrelated to qtx. Do some initial [troubleshooting](https://qtranslatexteam.wordpress.com/troubleshooting/) and let us know - in a new issue.

> I have another question... I read this:
> Download the latest Beta version of qTranslate-x Download it here
> ...
> So if I delete all and reinstall the plugin through FTP will I lose the translation I made before?

Where did you read this? Please, make a habit to cite the source in such a case. No, you will not lose translations, because they all are stored in the database. What is meant here, is that it is important to execute deactivation/activation hooks, instead of simple overwriting of files without deactivation/activation cycle, like some people are doing so save time. It works on simple plugins, which do nothing on activation, but this is not a case with qtx. It does expensive searches and possibly database changes on activation, which does not make sense to do every time on regular load. It is for the performance sake.

> I need also help how to translate manually mostly

That is called [integration](https://qtranslatexteam.wordpress.com/integration/).

Please, keep this issue closed unless you wish to talk more about "Internal Server Error".

**Comment by herrvigg** [comment]
<a href="https://github.com/blerimkrosi"><img src="https://avatars2.githubusercontent.com/u/5637169?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [blerimkrosi](https://github.com/blerimkrosi)**
_Thursday Oct 22, 2015 at 15:15 GMT_

----

Sorry I write here again but I dont know how can I contact private with you? I need help with integration..

**Comment by herrvigg** [comment]
<a href="https://github.com/johnclause"><img src="https://avatars2.githubusercontent.com/u/5491361?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [johnclause](https://github.com/johnclause)**
_Thursday Oct 22, 2015 at 16:12 GMT_

----

This means that you have not read any of links cited, because link to https://qtranslatexteam.wordpress.com/contact-us/ is scattered everywhere, basically on each possible page and maybe a few times per a page :smile:

**Comment by valerensi** [comment]
Hi, 
I still have this error with the latest version of qtranslate-xt
Sometimes the plugin change htaccess by adding lang parameters and caused an internal server error on frontend. Can you please have a look?
