### ISSUE TITLE
302 redirect on default language

### ISSUE THREAD

**Issue by herrvigg** [herrvigg/qtranslate-x#309]
<a href="https://github.com/ghost"><img src="https://avatars3.githubusercontent.com/u/10137?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ghost](https://github.com/ghost)**
_Wednesday Nov 11, 2015 at 18:09 GMT_
_Originally opened as https://github.com/qTranslate-Team/qtranslate-x/issues/309_

----

Hi!

I believe that I have found a bug.
The "qtranxf_init_language" method is performing a 302 redirect when I select the option: "Hide URL language information for default language.".

However, it would not be correct to add 301 as a parameter in wp_redirect?
Example: wp_redirect($target, 301) - line 81;

I say this for the sake of SEO.

http://example.com/default_lang/page.php ---> (302) http://example.com/page.php

Correct:

http://example.com/default_lang/page.php ---> (301) http://example.com/page.php

Can you could understand?

**Comment by herrvigg** [comment]
<a href="https://github.com/johnclause"><img src="https://avatars2.githubusercontent.com/u/5491361?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [johnclause](https://github.com/johnclause)**
_Thursday Nov 12, 2015 at 03:42 GMT_

----

Is this about one of these:

https://qtranslatexteam.wordpress.com/2015/02/26/browser-redirection-based-on-language/

https://github.com/qTranslate-Team/qtranslate-x/issues/306

The latter is a problem if you use caching plugin, the first one is "by design". Which one is your problem?

**Comment by amaycom** [comment]
The problem is still here.

If option "Hide URL language information for default language" is disabled, then all redirects are 302, but should be 301. Ai said so. And all SEO checkers dont like this.

What line in the code is responsible for this? I need to fix this urgently
