### ISSUE TITLE
Error when add/update post - Invalid argument supplied for foreach() - qtx_admin.php on line 14

### ISSUE THREAD

**Issue by herrvigg** [herrvigg/qtranslate-x#392]
<a href="https://github.com/nunospot"><img src="https://avatars3.githubusercontent.com/u/19820660?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [nunospot](https://github.com/nunospot)**
_Wednesday Jun 08, 2016 at 14:07 GMT_
_Originally opened as https://github.com/qTranslate-Team/qtranslate-x/issues/392_

----

I get a error when I try to add or update a post:

> Warning: Invalid argument supplied for foreach() in .../wp-content/plugins/qtranslate-x/admin/qtx_admin.php on line 14
> 
> Warning: Cannot modify header information - headers already sent by (output started at .../wp-content/plugins/qtranslate-x/admin/qtx_admin.php:14) in .../wp-includes/pluggable.php on line 1171

I saw a thread on wordpress support page with the same error -  https://wordpress.org/support/topic/warning-shown-on-page-update-qtranslate-xadminqtx_adminphp-on-line-14?replies=8

I'm using the workaround set by david.sota.ads, but like John Clause said this will only solve the error messages not the actual problem.

**Comment by herrvigg** [comment]
<a href="https://github.com/johnclause"><img src="https://avatars2.githubusercontent.com/u/5491361?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [johnclause](https://github.com/johnclause)**
_Wednesday Jun 08, 2016 at 22:21 GMT_

----

I still have no idea how that happens ... Probably older version of PHP is at fault, but what exactly is happening? Nobody troubleshooted it to the answer. We could never reproduce it and we have never gained an admin access to troubleshoot it. Would you have enough PHP skills to figure out what is going on?

**Comment by herrvigg** [comment]
<a href="https://github.com/nunospot"><img src="https://avatars3.githubusercontent.com/u/19820660?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nunospot](https://github.com/nunospot)**
_Thursday Jun 09, 2016 at 09:26 GMT_

----

I'm developing on my localhost, I didn't test it online yet, but I will give it a try. Anyway my php version is 4.6.1, so I don't think it's a php problem.

I'm using the qtranslate-x with the ACF to translate a several fields. I think the problem is when this fields are not filled so the $content on the foreach is NULL, in others words, the argument is invalid. And no, i'm not that good in PHP :\

**Comment by herrvigg** [comment]
<a href="https://github.com/johnclause"><img src="https://avatars2.githubusercontent.com/u/5491361?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [johnclause](https://github.com/johnclause)**
_Thursday Jun 09, 2016 at 14:34 GMT_

----

4.6.1 is pretty low by now.

NULL is what I do not understand, $content comes from $_POST, which should never have any nulls. Where this NULL come from? Sounds like an imperfection in ACF, which is not important anywhere else, but just causes this message. Could you try to figure out a simple reproducible case?

**Comment by herrvigg** [comment]
<a href="https://github.com/nunospot"><img src="https://avatars3.githubusercontent.com/u/19820660?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nunospot](https://github.com/nunospot)**
_Thursday Jun 09, 2016 at 15:33 GMT_

----

Yeah sorry, I was telling the phpMyAdmin version. The php is 5.5.19.

NULL I think comes from the fields that have not been filled.

**Comment by herrvigg** [comment]
<a href="https://github.com/johnclause"><img src="https://avatars2.githubusercontent.com/u/5491361?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [johnclause](https://github.com/johnclause)**
_Thursday Jun 09, 2016 at 15:40 GMT_

----

Yes, they apparently come from that, but it should not be a case. Empty fields come as empty strings, not NULL, in normal case. We can put "if(is_null(...)) ...", but it is strange to run an extra code just to offset either older PHP or imperfections in other plugin development? I would like to find out the true cause of this first. And for that I need a way to reproduce it.

**Comment by herrvigg** [comment]
<a href="https://github.com/nunospot"><img src="https://avatars3.githubusercontent.com/u/19820660?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nunospot](https://github.com/nunospot)**
_Thursday Jun 09, 2016 at 16:36 GMT_

----

I have the ACF pro version. I can give you access to the development in if you want.

**Comment by herrvigg** [comment]
<a href="https://github.com/johnclause"><img src="https://avatars2.githubusercontent.com/u/5491361?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [johnclause](https://github.com/johnclause)**
_Thursday Jun 09, 2016 at 16:46 GMT_

----

Access to localhost? I would think ACF Pro and regular would behave the same, as it seems basic. Could you describe the minimum steps to reproduce first? What kind of field one need to create and not to fill and where in order to see this message? Please, assume no knowledge of ACF for a reader. Maybe I will eventually able to reproduce on my localhost.

**Comment by herrvigg** [comment]
<a href="https://github.com/nunospot"><img src="https://avatars3.githubusercontent.com/u/19820660?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nunospot](https://github.com/nunospot)**
_Thursday Jun 09, 2016 at 17:04 GMT_

----

I have a dev environment on a server. What do you need specifically? I have several fields to fill (for example: text fields, wysiwyg editors, repeaters, images e etc) for this post and those fields, except the images, can be translated by the q-translate.

**Comment by herrvigg** [comment]
<a href="https://github.com/johnclause"><img src="https://avatars2.githubusercontent.com/u/5491361?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [johnclause](https://github.com/johnclause)**
_Thursday Jun 09, 2016 at 22:14 GMT_

----

I've never done anything with ACF and I would not like to spend time to learn. It would be great, if you could give me set of instructions what to do to see the error message you are seeing.

**Comment by herrvigg** [comment]
<a href="https://github.com/johnclause"><img src="https://avatars2.githubusercontent.com/u/5491361?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [johnclause](https://github.com/johnclause)**
_Friday Jun 10, 2016 at 14:31 GMT_

----

I tried a few fields, and I cannot hit this problem, never was able to to. If you wish to help, give us precise instructions what to do to reproduce, or [admin access](https://qtranslatexteam.wordpress.com/admin-access/) to a site with explanation what page to go and wht to do to observe the problem.

**Comment by herrvigg** [comment]
<a href="https://github.com/nunospot"><img src="https://avatars3.githubusercontent.com/u/19820660?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nunospot](https://github.com/nunospot)**
_Friday Jun 10, 2016 at 21:22 GMT_

----

Hi John, yeah ofc. I can't give you the access right because I don't have the access here you my personal computer, but monday on the work I can give it to you or reproduce another environment where you can see what going on.

**Comment by herrvigg** [comment]
<a href="https://github.com/nunospot"><img src="https://avatars3.githubusercontent.com/u/19820660?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nunospot](https://github.com/nunospot)**
_Monday Jun 13, 2016 at 11:25 GMT_

----

Hi john. Give me your email so I can send you the access.

**Comment by herrvigg** [comment]
<a href="https://github.com/johnclause"><img src="https://avatars2.githubusercontent.com/u/5491361?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [johnclause](https://github.com/johnclause)**
_Monday Jun 13, 2016 at 15:19 GMT_

----

The contact information is in the link I sent you: https://qtranslatexteam.wordpress.com/contact-us/

**Comment by herrvigg** [comment]
<a href="https://github.com/johnclause"><img src="https://avatars2.githubusercontent.com/u/5491361?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [johnclause](https://github.com/johnclause)**
_Wednesday Jun 15, 2016 at 02:26 GMT_

----

Thank you very much, @NC0sta, for setting up a test server for us.We would never be able to reproduce it on our servers, because it happens when a page has a hidden, unused translatable field and when user has the first language chosen when "Update" is pressed :+1: It happens with ACF mostly, but potentially can happen in other plugins too.

The fix is here: https://github.com/qTranslate-Team/qtranslate-x/commit/7586ff0d1186dbd5ba7a9529efe3333571243326
and it will be included in the next release.

**Comment by herrvigg** [comment]
<a href="https://github.com/riverofjanuary"><img src="https://avatars1.githubusercontent.com/u/1587594?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [riverofjanuary](https://github.com/riverofjanuary)**
_Thursday Sep 29, 2016 at 20:53 GMT_

----

FWIW I just installed the very latest version from the git repo (3.4.8) and had this exact error (on ACF site with fields moved around). I had to manually apply the "isset" fix (that @johnclause links to immediately above) to the `qtranxf_collect_translations` function and it fixed the problem... Was the fix applied to June 14 commit, then dropped out of a later version??

**Comment by herrvigg** [comment]
<a href="https://github.com/pwolfert"><img src="https://avatars2.githubusercontent.com/u/7595652?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [pwolfert](https://github.com/pwolfert)**
_Wednesday Oct 19, 2016 at 20:13 GMT_

----

I had the same problem as @riverofjanuary and saw that the fix is in the `stable` branch but not in `master`.  I've manually installed the latest `stable` version, and it fixed this and one other problem (https://piklist.com/support/topic/conflict-with-qtranslate-x-plugin-and-group-fields/).

**Comment by herrvigg** [comment]
<a href="https://github.com/dxit-gg"><img src="https://avatars3.githubusercontent.com/u/25633126?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dxit-gg](https://github.com/dxit-gg)**
_Tuesday Feb 21, 2017 at 13:47 GMT_

----

Hi there,
I have a similar problem with ACF.
I fix it with this code:

`function qtranxf_collect_translations( &$qfields, &$request, $edit_lang ) {
	if(isset($qfields['qtranslate-separator'])){
		$sep = $qfields['qtranslate-separator'];
		unset($qfields['qtranslate-separator']);
		$qfields[$edit_lang] = $request;
		$request = qtranxf_collect_translations_deep($qfields,$sep);
	}else{
		foreach($qfields as $nm => &$vals){
			if(!isset($request[$nm])){
				unset($request[$nm]);
				continue;
			}
			qtranxf_collect_translations($vals,$request[$nm],$edit_lang); // recursive call
		}
	}
}
`

Regards

**Comment by herrvigg** [comment]
<a href="https://github.com/fabianhijlkema"><img src="https://avatars3.githubusercontent.com/u/2919995?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [fabianhijlkema](https://github.com/fabianhijlkema)**
_Thursday Mar 02, 2017 at 13:40 GMT_

----

Had the same issue, @dxit-gg answer fixed it for me too. Also using ACF pro.

**Comment by herrvigg** [comment]
<a href="https://github.com/janeschindler"><img src="https://avatars3.githubusercontent.com/u/30444613?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [janeschindler](https://github.com/janeschindler)**
_Friday Feb 16, 2018 at 20:12 GMT_

----

I had two conflicts with ACF-qtranslate (the ACF integration plugin). 1) I got this error on line 14. Thank you for the fix (I haven't confirmed that it's working because I don't understand what you mean by 'first language' in this comment: https://github.com/qTranslate-Team/qtranslate-x/issues/392#issuecomment-226071534. I have the issue but haven't been able to reproduce reliably. Would be great if you could clarify). 2) When I edited and saved group ACF fields, the fields I had put inside groups were all replicated outside the groups but without field names (https://github.com/funkjedi/acf-qtranslate/issues/111). After a quick test this also seems to have been fixed. Is that possible? I really hope it doesn't happen any more.

**Comment by herrvigg** [comment]
<a href="https://github.com/janeschindler"><img src="https://avatars3.githubusercontent.com/u/30444613?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [janeschindler](https://github.com/janeschindler)**
_Sunday Feb 18, 2018 at 21:47 GMT_

----

I am using the stable branch now with the fix and just had this error again (invalid argument on line 14). My site deletes the entirety of the post in the language that's being edited (but not the other languages). I've upped the max_input_vars for php and hope that might help. Very glad if anyone has other ideas.

**Comment by Marko-Markovic** [comment]
Hey everyone!

I'm still experiencing the issue as the fix by @dixit-gg did not work for me. It simply bypasses the error while avoiding to save any fields or rows beyond the "affected" one which returns empty brackets.

I'm running the following:

q-Translate-X Version 3.4.6.8
Advanced Custom Fields: qTranslate 1.7.23
Advanced Custom Fields PRO 5.6.10

Am I missing something aside from applying the provided code in the qt-admin.pp ?

**Comment by Marko-Markovic** [comment]
Update:

As I seem to have used quite a lot of fields, and this occurred in out of the box local web server it never occurred to me that the limits might be needed. After upping the memory limits of php/wp the issue did not reappear (no other changes were made).
